### ISSUE TITLE
Problem with namespaced CSS for XML

### ISSUE THREAD

**Issue by bmix** [sandorengholm/csspreview#9]
When writing CSS (see below for full code) for XML I get the following:

![cssprev](https://user-images.githubusercontent.com/310157/114113387-c0382a00-98de-11eb-8d6f-988de88ac032.jpg)

```css
@namespace html url("http://www.w3.org/1999/xhtml");
@namespace jsd url("http://usejsdoc.org");
@namespace xml url("http://www.w3.org/XML/1998/namespace");

* { 
  padding-left: 1rem;
  display: block;
  border: 1px solid grey;
}
*[xml|space='preserve'] { white-space: pre; }
*[xml|space='default'] { white-space: normal; }

jsd|jsdoc { 
  font-size: 12pt;
  font-family: sans-serif;
  padding: 1rem 1rem 1rem 1rem;
}
jsd|examples {
  margin: 1rem 2rem;
}
jsd|namespaces {}
jsd|namespaces > name { 
  font-size: 1.3rem; 
  font-weight: 600;
  padding: 1rem 1rem 1rem 1rem;
  }
jsd|name { font-weight: 600; }
jsd|description {
  max-width: 40rem;
}
jsd|access {}
jsd|virtual {}
jsd|virtual::before {
  content: "virtual";
}
jsd|functions {}
jsd|functions jsd|name { font-family: monospace; }
jsd|returns {}
jsd|parameters { background-color: #f0f0f0; }
jsd|parameters jsd|name, jsd|parameters jsd|type, jsd|returns jsd|type {
    font-family: monospace;
    display: inline;
    padding: 0;
}
jsd|type {}
jsd|default {}
jsd|optional {}
jsd|nullable {}
html|p {}
html|pre { white-space: pre; }
html|code { font-family: monospace; display: inline; padding: 0; }
html|em { font-variant: italic; display: inline; padding: 0; }
html|a { 
  padding: 0;
  display: inline;
  text-decoration: underline;
  color: blue;
}
a:hover {
  text-decoration: none;
  cursor: pointer;
}
a:visited {
  text-decoration: underline;
  color: aqua;
}

html|style { display: none; }
```

See also:

* https://www.w3.org/Style/styling-XML.en.html
